sudo: false
language: node_js
node_js:
- '8'
script:
- "./command.sh install"
deploy:
  provider: npm
  email: j.lopez.r@gmail.com
  api_key:
    secure: p3RQTgS/6JcXY3a26zYjPOy75EeH/hU2gXSMaHNeAN86DHXBbiXWKhMnbvoPgau91CHc009plSx+I12HSroBt/M6nRALODPE/2uG8EJkeQVKO+mZabYnZc+oTNbi5BH+UkoHSRT7lnJ0WFAq/Q2KfBvG6GASB5LyyL8xq71sgCuNeMmnCEaQZ1jlJnBUNL8JZOG0m1pXu85g9arkKbtqnBMzefObM+TIGSbwzuOlhysM2JzbpVp+1JMNYhTV1BvzU2QDo8dr5K7KSCbtSSs6bY+Cy8jAYqw0amOSfLk2H1Ygedu0DrJ97by46Gayavrs5O4GnRes/PmkY+NZ/TvBpxHcAksAglDs1jfgouxtlQ3UGFPmbPrQo50vHGHJGNAFQ24xG+pBId5UmrIr63ZejKEJEUM9XB4JhKLhboVeo5apaRppsjZimUhMXYVIDWKlc5DgrQkBSeKikLzgFpQXAQdYRky2+Y3a8kOtIpSqAkuBXSsd8ihx5lysPC6yExp9/skp0tju7CpvuOFemzxAbFixPne8VqcXamKHSfMFZq4swGukHNN8I2aQ5sk1Q3qR0azz56pz+DSHNz6suUqebkiv634ivmCC/VmrbDlopIiS9Lm1x6BvWaae00fzlBJZVaz14bW6ixXZ1IdDk4/ojdSur8m246dBE7HQmE7JQSg=
  on:
    tags: true
    repo: RouteInjector/ri-backoffice
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: md0LdTHXFkbgRytuYn389fR/NI+sbnvQHJj3CKWAlhtwpw2jD2YdxUFJQv/la3fxDOVyfbkmhltd1lsyakqO6ak/JC42NkLAzbno3f35FVAcpthroLOd4RAFzcN3vSWZwdzBcAayUOElEkvc4nafu5MkTJ5PaS3drazeV7CRuF/OBECW2UpADYFwOjzvm5zT5FO7Ymb4LCdJ5PdvDyNnCY/6pmS1jAX4YK7mlN6N6+dhuNAgsbKFSElmn11qLwklKge7yFC+KPxu28UZhkr53NBZTtOEf7tt9dm9vr2y2OeMJqckmFw5FlaBdP0PjfgOExyULF+jH6YdbKnruoKXNuDEG/rSutAnhZtpQG9e6OnJC7BtjlvJIo3AXKtrz/MyKR5yguQ5fqHrysYt2Lk7CYwWOJS38EY36UYJHFPduT9NoFhCkGSWKlWRgZdt89GoT2wzhXW2L5/lRpfsPaUayOwUkrc9eu0owhA2Z6wXp4wdlkQDHgoXZ93jY5JsuFyDOobtg2oBDQT/NSjAPNt/SLyY2B5cS0CuGzln5x/W0XJ8law4YUHcCVBqPC3m7SNABQdkMiNmevc5UJITWnfA2+3k3lRvZWG9yUGadiFNB+9bco3aDB4gBu4YyG5yipchJiitd5XjR/aV4hqugmAz6wDAbDkxz5+EttJf6SLfD18=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
